// Newest entry first. `date` (ISO) is the sort key; `displayDate` is what renders.
export const changelog = [
  {
    date: '2026-08-02',
    displayDate: '02 Aug 2026',
    tag: 'New',
    title: 'PDF to Word — Exact Layout mode',
    description: 'New conversion mode that keeps every page looking pixel-identical to the PDF (as full-page images, not editable text). Editable mode also gained centered/right alignment detection and true font sizes.',
    link: '/pdf-to-word/',
    quote: null,
  },
  {
    date: '2026-08-02',
    displayDate: '02 Aug 2026',
    tag: 'Improved',
    title: 'PDF to Word — much better tables',
    description: 'Rebuilt table detection from user feedback: paragraphs no longer get chopped into fake tables, side-by-side tables split correctly, and spanning headers merge properly. Large PDFs no longer freeze the tab, and clear limits and error messages were added across the PDF and image tools.',
    link: '/pdf-to-word/',
    quote: null,
  },
  {
    date: '2026-08-02',
    displayDate: '02 Aug 2026',
    tag: 'New',
    title: 'Share buttons',
    description: 'Every tool page now has quick share buttons — WhatsApp, X, LinkedIn, email or copy the link.',
    link: null,
    quote: null,
  },
  {
    date: '2026-07-20',
    displayDate: '20 Jul 2026',
    tag: 'New',
    title: 'Feedback widget',
    description: 'Added a quick way to tell us what calculator you wish existed. We read every submission.',
    link: null,
    quote: null,
  },
  {
    date: '2026-07-15',
    displayDate: '15 Jul 2026',
    tag: 'New',
    title: 'Stock Profit Calculator',
    description: 'Net share trading profit after brokerage, STT, GST and capital gains tax.',
    link: '/stock-profit-calculator/',
    quote: null,
  },
  {
    date: '2026-07-09',
    displayDate: '09 Jul 2026',
    tag: 'New',
    title: 'MF Profit Calculator',
    description: 'Search any Indian mutual fund and see real profit, XIRR and tax on gains.',
    link: '/mf-profit-calculator/',
    quote: null,
  },
  {
    date: '2026-07-03',
    displayDate: '03 Jul 2026',
    tag: 'New',
    title: 'Changelog',
    description: "Added this page, so you can see what's new and what's changed — including things based on your feedback.",
    link: null,
    quote: null,
  },
];
