'use client';
import { useState, useRef } from 'react';
import CrossBrandCard from '../components/CrossBrandCard';

const SAMPLE = `<h1 style="color:#1e3a8a;font-family:Arial">My Document</h1>
<p style="font-family:Arial;font-size:14px">This is a sample paragraph. Replace this with your own HTML content.</p>
<ul style="font-family:Arial;font-size:14px">
  <li>Item one</li>
  <li>Item two</li>
  <li>Item three</li>
</ul>
<p style="font-family:Arial;font-size:12px;color:#666">Generated by TechSolve44</p>`;

export default function HTMLToPDF() {
  const [html, setHtml]     = useState(SAMPLE);
  const [tab, setTab]       = useState('editor'); // 'editor' | 'preview'
  const [loading, setLoading] = useState(false);
  const [error, setError]   = useState('');
  const containerRef        = useRef(null);

  const convert = async () => {
    setLoading(true); setError('');
    try {
      // Dynamically load html2pdf.js from CDN
      await new Promise((resolve, reject) => {
        if (window.html2pdf) { resolve(); return; }
        const script = document.createElement('script');
        script.src = 'https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js';
        script.onload = resolve;
        script.onerror = reject;
        document.head.appendChild(script);
      });

      const el = document.createElement('div');
      el.style.cssText = 'position:fixed;left:-9999px;top:0;width:794px;background:#fff;padding:40px;';
      el.innerHTML = html;
      document.body.appendChild(el);

      await window.html2pdf().set({
        margin: 10,
        filename: 'document.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
      }).from(el).save();

      document.body.removeChild(el);
    } catch (e) {
      setError('Conversion failed: ' + e.message);
    }
    setLoading(false);
  };

  return (
    <div className="tool-container">
      <h1 className="text-2xl md:text-3xl font-extrabold text-slate-800 mb-1">HTML to PDF</h1>
      <p className="text-slate-500 mb-8 text-sm">Paste or write HTML and download it as an A4 PDF. Runs entirely in your browser.</p>
      {error && <div className="mb-4 bg-red-50 border border-red-200 rounded-xl p-4 text-sm text-red-700">⚠️ {error}</div>}

      {/* Tabs */}
      <div className="flex gap-1 mb-4 bg-slate-100 rounded-xl p-1 w-fit">
        {['editor','preview'].map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={`px-5 py-2 rounded-lg text-sm font-semibold transition-colors capitalize ${tab===t ? 'bg-white text-brand-700 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}>
            {t === 'editor' ? '✏️ Editor' : '👁️ Preview'}
          </button>
        ))}
      </div>

      {tab === 'editor' ? (
        <textarea value={html} onChange={e => setHtml(e.target.value)} spellCheck={false}
          className="w-full h-72 font-mono text-sm border border-slate-200 rounded-2xl p-4 focus:outline-none focus:ring-2 focus:ring-brand-400 resize-y bg-slate-50" />
      ) : (
        <div className="w-full min-h-72 border border-slate-200 rounded-2xl p-6 bg-white overflow-auto"
          dangerouslySetInnerHTML={{ __html: html }} />
      )}

      <button onClick={convert} disabled={loading || !html.trim()}
        className="mt-5 w-full py-4 bg-brand-700 hover:bg-brand-800 disabled:bg-slate-300 text-white font-bold rounded-xl transition-colors">
        {loading ? '⏳ Generating PDF…' : '📄 Convert to PDF & Download'}
      </button>

      <div className="mt-8 bg-slate-50 rounded-2xl p-5">
        <h2 className="text-base font-bold text-slate-700 mb-3">Tips for best results</h2>
        <ul className="space-y-1.5 text-sm text-slate-600">
          <li>✅ Use inline CSS styles (e.g. <code className="bg-slate-200 px-1 rounded text-xs">style="font-family:Arial"</code>)</li>
          <li>✅ External CSS and Google Fonts may not load — embed styles inline</li>
          <li>✅ Images must be hosted online (http/https URLs) or base64 encoded</li>
          <li>✅ Keep content within A4 width (~794px) for best layout</li>
        </ul>
      </div>

      <CrossBrandCard pageSlug="html-to-pdf" />
    </div>
  );
}
